---
output:
  html_document: default
---

# Presentación sintética de todos los scripts

A continuación se presentan de manera sintética todos los scripts que constituyen el SIDIL.

+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Nombre (sin incluir versionado)** | **Módulo** | **Objetivo**                                                                                                                                                                | **Observaciones**                                                                                                                                   | **Lenguaje** | **Principales insumos**                                                                                                         | **Principales outputs**                                                                                                                                            |
+:====================================+:===========+:============================================================================================================================================================================+:====================================================================================================================================================+:=============+:================================================================================================================================+:===================================================================================================================================================================+
| 0_config_inicial                    | I a IV     | Carga de paqueterías para ambiente R;\                                                                                                                                      | Es ejecutado por prácticamente todos los scripts secuenciadores                                                                                     | R            | NA                                                                                                                              | Parámetros cargados en la memoria RAM                                                                                                                              |
|                                     |            | Define parámetros de explotación de información                                                                                                                             |                                                                                                                                                     |              |                                                                                                                                 |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 0_funciones_catalogos               | I a IV     | Define funciones                                                                                                                                                            | A excepción del script 9_envio_MPR, este script siempre es llamado por 0_config_inicial                                                             | R            | Catálogos de información                                                                                                        | Catálogos cargados y funciones definidas en la RAM.                                                                                                                |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_secuenciador_ENOE                 | I          | Ejecuta toda la rutina para generar los indicadores coyunturales de la ENOE                                                                                                 | Es el único script que se debe ejecutar, ya que este llama a los otros scripts                                                                      | R            | Script de configuración inicial; catálogos; script de extracción; scripts de generación de indicadores                          | Una tabla por cada indicador calculado con las estimaciones puntuales de dicho indicador. Una tabla con los valores de referencia de cada indicador.               |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_extraccion_ENOE                   | I          | Construye la base de insumo para el cálculo de los indicadores de la ENOE a partir de las bases originales en formato .dbf                                                  | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | Tablas originales de la ENOE en formato .dbf                                                                                    | Una tabla unificada de la ENOE en formato .dbf con la población subordinada y reumunerada                                                                          |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_brecha_gen_ENOE                   | I          | Genera las estimaciones puntuales coyunturales del indicador "brecha de género" de la ENOE                                                                                  | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | La tabla resultado del script de extracción                                                                                     | Una tabla con las estimaciones puntuales del respectivo indicador.                                                                                                 |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_contrato_escrito_ENOE             | I          | Genera las estimaciones puntuales coyunturales del indicador "contrato escrito" de la ENOE                                                                                  | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | La tabla resultado del script de extracción                                                                                     |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_dias_trab_ENOE                    | I          | Genera las estimaciones puntuales coyunturales del indicador "días trabajados" de la ENOE                                                                                   | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | La tabla resultado del script de extracción                                                                                     |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_hrs_trab_ENOE                     | I          | Genera las estimaciones puntuales coyunturales del indicador horas trabajadas" de la ENOE                                                                                   | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | La tabla resultado del script de extracción                                                                                     |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_ing_min_ENOE                      | I          | Genera las estimaciones puntuales coyunturales del indicador "ingreso mínimo" de la ENOE                                                                                    | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | La tabla resultado del script de extracción                                                                                     |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_ing_x_hrs_ENOE                    | I          | Genera las estimaciones puntuales coyunturales del indicador "ingreso por hraso" de la ENOE                                                                                 | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | La tabla resultado del script de extracción                                                                                     |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_ing_x_mes_ENOE                    | I          | Genera las estimaciones puntuales coyunturales del indicador "ingreso por mes" de la ENOE                                                                                   | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | La tabla resultado del script de extracción                                                                                     |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_presta_soc_ENOE                   | I          | Genera las estimaciones puntuales coyunturales del indicador "prestaciones sociales" de la ENOE                                                                             | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | La tabla resultado del script de extracción                                                                                     |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_seg_soc_ENOE                      | I          | Genera las estimaciones puntuales coyunturales del indicador "seguridad social" de la ENOE                                                                                  | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | La tabla resultado del script de extracción                                                                                     |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_sindicato_ENOE                    | I          | Genera las estimaciones puntuales coyunturales del indicador "sindicato" de la ENOE                                                                                         | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | La tabla resultado del script de extracción                                                                                     |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_tipo_contrato_ENOE                | I          | Genera las estimaciones puntuales coyunturales del indicador "tipo contrato" de la ENOE                                                                                     | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | La tabla resultado del script de extracción                                                                                     | Una tabla con las estimaciones puntuales del indicador.                                                                                                            |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_secuenciador_CENSO2019            | I          | Ejecuta toda la rutina para generar los indicadores del Censo Económico                                                                                                     | Es el único script del Censo Económico                                                                                                              | R            | Tabla de datos de las 3 empresas más grandes a nivel municipal y rama (SCIAN 2 dígitos), producto de la colaboración INEGI-STPS | Una tabla por cada indicador calculado con las estimaciones puntuales de dicho indicador.                                                                          |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_secuenciador_IMSS                 | I          | Ejecuta toda la rutina para generar los indicadores del IMSS                                                                                                                | Es el único script que se debe ejecutar, ya que este llama a los otros scripts                                                                      | R            | Script de configuración inicial; catálogos; script de extracción; scripts de generación de indicadores                          | Una tabla por cada indicador calculado con las estimaciones puntuales de dicho indicador. Una tabla con los valores de referencia de cada indicador.               |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_extraccion_IMSS                   | I          | Construye la base de insumo para el cálculo de los indicadores del IMSS                                                                                                     | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | Insumos originales del IMSS: accidenes (riesgos), patrones y puestos (asegurados)                                               | Una tabla para cada insumo original por mes, además para puestos, una tabla adicional con los NSS de las personas aseguradas, también por mes.                     |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_brecha_imss                       | I          | Genera las estimaciones puntuales coyunturales del indicador "brecha salarial de género" del IMSS                                                                           | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | Insumos procesados, combinados selectivamente desde el secuenciador.                                                            | Estimaciones puntuales en dos tablas: por nivel de agregación y nominativo, para cada mes.                                                                         |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_concen_mercado_imss               | I          | Genera las estimaciones puntuales coyunturales del indicador "concentración de mercado" del IMSS                                                                            | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | Insumos procesados, combinados selectivamente desde el secuenciador.                                                            |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_rot_lab                           | I          | Genera las estimaciones puntuales coyunturales del indicador "rotación laboral" del IMSS                                                                                    | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | Insumos procesados, combinados selectivamente desde el secuenciador.                                                            |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_salario_minimo                    | I          | Genera las estimaciones puntuales coyunturales del indicador "rotación laboral" del IMSS                                                                                    | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | Insumos procesados, combinados selectivamente desde el secuenciador.                                                            |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_tasa_acc                          | I          | Genera las estimaciones puntuales coyunturales del indicador "rotación laboral" del IMSS                                                                                    | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | Insumos procesados, combinados selectivamente desde el secuenciador.                                                            |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_tasa_dias                         | I          | Genera las estimaciones puntuales coyunturales del indicador "rotación laboral" del IMSS                                                                                    | Se ejecuta automáticamente desde el script secuenciador                                                                                             | R            | Insumos procesados, combinados selectivamente desde el secuenciador.                                                            |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2_consulta_DNE\_                    | II         | Organiza la consulta al DNE (como secuenciador) y enriquece la categoría de tamaño con base en los patrones registrados ante el IMSS.                                       |                                                                                                                                                     | R            | DNE y Patrones del IMSS                                                                                                         | DNE_plus: universo de CT consultado del DNE.                                                                                                                       |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2_conexion                          | II         | Establece la conexión al SQL Server.                                                                                                                                        | Se ejecuta automáticamente desde 2_consulta_DNE                                                                                                     | R            | Credenciales de acceso a SQL Server                                                                                             | Conexión a DNE en la RAM                                                                                                                                           |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2_extraccion_DNE                    | II         | Formula y envía queries para extraer tablas del SQL Server                                                                                                                  | Se ejecuta automáticamente desde 2_consulta_DNE                                                                                                     | R            | Catálogo de campos del DNE                                                                                                      | Tablas consultadas al DNE, en la RAM                                                                                                                               |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2_matching_coyuntural\_             | II         | Imputa de manera nominativa y por nivel de agregación los indicadores coyunturales al DNE_plus                                                                              |                                                                                                                                                     | Python       | DNE_plus                                                                                                                        | Universo CT con indicadores coyunturales imputados                                                                                                                 |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2_prediccion_modelo\_               | II         | Genera predicción de riesgos por submateria y general                                                                                                                       |                                                                                                                                                     | Python       | Universo CT con indicadores coyunturales imputados                                                                              | Matriz de predicción de riesgos                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| automatizacion/app.R                | I y II     | Es la app de la interfaz de automatización que organiza la actualización de fuentes de información, carga de catálogos y la ejecución de los scripts en los módulos I y II. | La interfaz únicamente permite la realización de procesos del módulo I y II.                                                                        | R            | Todos los scripts y fuentes de información de los módulos I y II                                                                | Todos los outputs de los módulos I y II                                                                                                                            |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| consulta/app.R                      | III        | Es la app de la interfaz de consulta que permite priorizar los CT con base en sus predicciones de riesgo, atributos e indicadores                                           |                                                                                                                                                     | R            | Matriz de predicción de riesgos                                                                                                 | Universo de CT que satisfacen criterios de inspección                                                                                                              |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4_query_violaciones_inspecciones\_  | IV         | Organiza la consulta al SIAPI-SIPAS                                                                                                                                         | Incluye la consulta al universo de CT para recuperar atributos de los mismos                                                                        | R            | Credenciales de acceso a SQL Server                                                                                             | Historico de inspecciones por submateria incluyendo si se encontraron violaciones que proceden                                                                     |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4_secuenciador_ENOE                 | IV         | Ejecuta toda la rutina para generar los indicadores coyunturales de la ENOE                                                                                                 | Es el único script que se debe ejecutar, ya que este llama a los otros scripts                                                                      | R            | Script de configuración inicial; catálogos; script de extracción; scripts de generación de indicadores                          | enoe_historico_v.Rds: una sola tabla con todos los indicadores para todos los años.                                                                                |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4_extraccion_ENOE                   | IV         | Construye la base de insumo para el cálculo de los indicadores de la ENOE a partir de las bases originales en formato .dbf                                                  | La unica diferencia respecto a este script del módulo I es que en el módulo IV se incluye el año.                                                   | R            | Tablas originales de la ENOE en formato .dbf                                                                                    | Una tabla unificada de la ENOE en formato .dbf con la población subordinada y reumunerada, con el año                                                              |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4_brecha_gen_ENOE                   | IV         | Genera las estimaciones puntuales coyunturales del indicador "brecha de género" de la ENOE                                                                                  |                                                                                                                                                     | R            | La tabla resultado del script de extracción.                                                                                    | El cálculo por año para cada indicador, mismo que luego el secuenciador "apila" para conformar una sola tabla con todos los indicadores.                           |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4_contrato_escrito_ENOE             | IV         | Genera las estimaciones puntuales coyunturales del indicador "contrato escrito" de la ENOE                                                                                  |                                                                                                                                                     | R            |                                                                                                                                 |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4_dias_trab_ENOE                    | IV         | Genera las estimaciones puntuales coyunturales del indicador "días trabajados" de la ENOE                                                                                   |                                                                                                                                                     | R            |                                                                                                                                 |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4_hrs_trab_ENOE                     | IV         | Genera las estimaciones puntuales coyunturales del indicador horas trabajadas" de la ENOE                                                                                   |                                                                                                                                                     | R            |                                                                                                                                 |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4_ing_x_hrs_ENOE                    | IV         | Genera las estimaciones puntuales coyunturales del indicador "ingreso por hraso" de la ENOE                                                                                 |                                                                                                                                                     | R            |                                                                                                                                 |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4_ing_x_mes_ENOE                    | IV         | Genera las estimaciones puntuales coyunturales del indicador "ingreso por mes" de la ENOE                                                                                   |                                                                                                                                                     | R            |                                                                                                                                 |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4_presta_soc_ENOE                   | IV         | Genera las estimaciones puntuales coyunturales del indicador "prestaciones sociales" de la ENOE                                                                             |                                                                                                                                                     | R            |                                                                                                                                 |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4_seg_soc_ENOE                      | IV         | Genera las estimaciones puntuales coyunturales del indicador "seguridad social" de la ENOE                                                                                  |                                                                                                                                                     | R            |                                                                                                                                 |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4_sindicato_ENOE                    | IV         | Genera las estimaciones puntuales coyunturales del indicador "sindicato" de la ENOE                                                                                         |                                                                                                                                                     | R            |                                                                                                                                 |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4_tipo_contrato_ENOE                | IV         | Genera las estimaciones puntuales coyunturales del indicador "tipo contrato" de la ENOE                                                                                     |                                                                                                                                                     | R            |                                                                                                                                 |                                                                                                                                                                    |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1_secuenciador_IMSS                 | IV         | Ejecuta toda la rutina para generar los indicadores del IMSS                                                                                                                | La unica diferencia respecto a este script del módulo I es en la configuración de parámetros                                                        | R            | Script de configuración inicial; catálogos; script de extracción; scripts de generación de indicadores                          | Una tabla por cada indicador calculado con las estimaciones puntuales de dicho indicador. Una tabla con los valores de referencia de cada indicador.               |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4_matching_historico                | IV         | Imputa de manera nominativa y por nivel de agregación los indicadores históricos de IMSS y ENOE al histórico de inspecciones                                                |                                                                                                                                                     | Python       | Tablas de indicadores históricos del IMSS y de la ENOE; histórico de inspecciones por submateria que incluye atributos del DNE  | UniversoInspeccionesInd_v.Rds: una tabla que a cada inspección y submateria le asocia los valores históricos del IMSS y ENOE, además de los atributos del DNE.     |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4_entrenamiento_modelo              | IV         | Entrena el modelo random forest con base en el histórico de inspecciones.                                                                                                   | Se pueden entrenar dos modelos, actualmente predefinido para que sea Random Forest. La alternativa es el Tabnet (red neuronal para datos tabulares) | Python       | UniversoInspeccionesInd_v.Rds                                                                                                   | Modelo entrenado, exportado a archivos pkl, un txt con las variables de entrada del modelo, score y submateria con la métrica de ajuste de las predicciones (MAE). |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4_eval_modelo                       | IV         | Genera métricas de performance del modelo y análisis Shapley (medición de contribución relativa de variables de entrada).                                                   |                                                                                                                                                     | Python.      | El modelo entrenado y la base histórica de inspecciones por submateria.                                                         | Dos tablas reportadas en el log con las métricas de performance.\                                                                                                  |
|                                     |            |                                                                                                                                                                             |                                                                                                                                                     |              |                                                                                                                                 | Imágenes (png) con el análisis Shapley, mismas que además conforman un html.                                                                                       |
+-------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
